### ISSUE TITLE
JSON bleeding into results table with file uploads

### ISSUE THREAD

**Issue by mbernst** [crowdresearch/daemo#928]
I see this with the uploaded file:
<img width="307" alt="screen shot 2017-07-24 at 10 56 52 am" src="https://user-images.githubusercontent.com/249285/28537185-dfdeb9fc-705e-11e7-97a7-4901c5b19c64.png">

Ideally what we want is a link to the uploaded file.

**Comment by dmorina** [comment]
done

**Comment by mbernst** [comment]
I'm still seeing this:

Project 88:
<img width="260" alt="screen shot 2017-07-24 at 9 03 21 pm" src="https://user-images.githubusercontent.com/249285/28555270-9e116808-70b3-11e7-938a-dc5c9d681738.png">

**Comment by dmorina** [comment]
CNN? Try clearing cache
<img width="1439" alt="screen shot 2017-07-24 at 9 07 32 pm" src="https://user-images.githubusercontent.com/2858281/28555346-34c837ae-70b4-11e7-8518-517ff3a70ecc.png">
